name: Update Database with Liquibase

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  update-database:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11' # Match the version required by Liquibase

    - name: Install Liquibase
      run: |
        # Fetch the latest version of Liquibase (replace with the correct URL)
        wget https://github.com/liquibase/liquibase/releases/download/v4.20.0/liquibase-4.20.0.tar.gz
        tar -xvzf liquibase-4.20.0.tar.gz
        sudo mv liquibase /usr/local/bin/

    - name: Verify Liquibase Installation
      run: liquibase --version

    - name: Run Liquibase Update
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        liquibase \
          --changeLogFile=dbchangelog5.xml \
          --url="jdbc:mysql://localhost:3306/UsersData" \
          --username="${DB_USERNAME}" \
          --password="${DB_PASSWORD}" \
          --driver="com.mysql.cj.jdbc.Driver" \
          update
